deploy
papiyan98/AOByte-Intership-Arsen-Papiyan pull request #4
Opened 2023-07-11 14:57 UTC by papiyan98

2023-07-12 07:03 UTC, ao-alexi requested changes
hi Arsen,
1. per requirement, the app should show the pool of posts with comments, then you add them to lists and they get visually disabled in the pool. Could you add that?

2. to take full advantage of React your app should be divided into separate components, then you can reuse both UI elements and their behavior. notice how the render method of App.js describes two identical lists: whenever you see repetition like that means you can separate it into a component.

2023-07-12 10:45 UTC, papiyan98 commented
> hi Arsen,
> 
>     1. per requirement, the app should show the pool of posts with comments, then you add them to lists and they get visually disabled in the pool. Could you add that?
> 
>     2. to take full advantage of React your app should be divided into separate components, then you can reuse both UI elements and their behavior. notice how the render method of App.js describes two identical lists: whenever you see repetition like that means you can separate it into a component.

Hi Alex,

This task doesn't require to display the pool. I talked to Stepan, it will be in the next task.

I also divided the render method in App.js into separate components, and now each list is a separate component.

2023-07-17 09:24 UTC, ao-alexi reviewed
hi Arsen,
whenever you need to change DOM like changing an element's text/src, adding new elements or removing them, try to make according changes to the state and let React render the page accordingly instead of using the document object. you'll write much less code and React will apply necessary optimizations

2023-07-19 16:05 UTC, papiyan98 commented
This application update includes ability to dynamically add and delete comments․ Each post has the ability to sort comments by their age and rating (ASC and DESC). Each comment has ability to reply (only 1 level). Also app design modified.

2023-07-19 18:23 UTC, aokareng requested changes
Arsen jan There are some changes that You could write better, but In general concepts, code quality, and code compositions are good.

2023-07-19 18:23 UTC, aokareng commented on homework-React/src/components/CommentForm/CommentForm.js
> +    if (event.target.className.includes("Reply")) {
I think this is complex Logic, You could write better

2023-07-19 18:23 UTC, aokareng commented on homework-React/src/components/CommentReply/CommentReply.js
> +    this.props.updateCommentReplyRate(this.props.postId, this.props.commentIndex, this.props.reply, +newRate);
Again, destructure props before usage, to avoid multiple duplications this.props

2023-07-19 18:23 UTC, aokareng commented on homework-React/src/components/CommentReply/CommentReply.js
> +      <div className="repliedComment">
why camelCase?

2023-07-19 18:23 UTC, aokareng commented on homework-React/src/components/CustomSelect/CustomSelect.js
> +class CustomSelect extends Component {
It is great that You can create a custom Select Arsen jan, but in the future try to always use some built-in selects from NPM. Because it is much more reliable and tested thousands times.

2023-07-19 18:23 UTC, aokareng commented on homework-React/src/components/PostPreview/PostPreview.js
> +            {parseFloat(+(calcPostAverageRate(post)).toPrecision(2))}
Try to avoid calling these calculations in JSX, It will be better to move into some functions Eg, 
finalAvarageRateCalculation()

2023-07-19 18:23 UTC, aokareng commented on homework-React/src/components/PostsBoard/PostsBoard.js
> +    if (searchedPosts.length) {
You could have better condittion,
const postsList = searchedPosts.length > 0 ? searchedPosts : pool;

then just use Post component once.
return (
...
postsList.map(... <Post>...)
)

2023-07-19 21:45 UTC, papiyan98 commented
> Arsen jan There are some changes that You could write better, but In general concepts, code quality, and code compositions are good.

Suggested changes have been successfully applied, thanks.

2023-07-23 14:20 UTC, papiyan98 commented
This app update includes server binding, pagination, client side routing. All React components changed to Functional. For sign in is used sessionStorage. The functionality of the SignUp component is in process.

2023-07-30 10:03 UTC, merged